In [88]:
import numpy as np


In [90]:
array1d=na.array([2,4,6,3,1])
print(array1d)
print(type(array1d))

[2 4 6 3 1]
<class 'numpy.ndarray'>


In [91]:
array2d=np.array([[2,3,4],[5,6,7]])
print(array2d)
print(type(array2d))

[[2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>


In [9]:
li=[9,87,7]
print(li)
print(type(li))

[9, 87, 7]
<class 'list'>


In [14]:
li=[1,4,9,'g','l']
print(type(li))
result=np.array(li)
print(result)
print(type(result))
result

<class 'list'>
['1' '4' '9' 'g' 'l']
<class 'numpy.ndarray'>


array(['1', '4', '9', 'g', 'l'], dtype='<U11')

In [17]:
output=np.arange(21)
print(output)
output

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [20]:
output=np.arange(100000)
print(output)
output

[    0     1     2 ... 99997 99998 99999]


array([    0,     1,     2, ..., 99997, 99998, 99999])

In [23]:
output=np.arange(10000)
print(output)


[   0    1    2 ... 9997 9998 9999]


In [24]:
a=np.arange(10000).reshape(100,100)
a

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [38]:
array1=np.random.randint(5,9,size=(3,3,3,3))
print(array1)
print("shape :",array1.shape)
print("size :",array1.size)
print("dtype :",array1.dtype)
print("Item Size :",array1.itemsize)
print("Data :",array1.data)
print("Ndim :",array1.ndim)

[[[[8 5 8]
   [5 8 5]
   [5 6 5]]

  [[6 7 7]
   [8 5 5]
   [7 5 5]]

  [[7 5 7]
   [8 6 5]
   [6 6 6]]]


 [[[5 6 7]
   [6 8 8]
   [8 7 6]]

  [[6 7 8]
   [8 8 6]
   [6 5 7]]

  [[8 8 8]
   [5 7 7]
   [7 7 6]]]


 [[[7 8 6]
   [7 8 8]
   [7 6 7]]

  [[6 5 5]
   [7 8 5]
   [5 5 5]]

  [[5 6 8]
   [5 7 5]
   [7 8 6]]]]
shape : (3, 3, 3, 3)
size : 81
dtype : int32
Item Size : 4
Data : <memory at 0x0000015DAC11D360>
Ndim : 4


In [44]:
array1=[[1,2,3,4],[5,9,8,7]]
type(array1)

list

In [46]:
res=np.array(array1)
print(type(res))

<class 'numpy.ndarray'>


In [48]:
import numpy as np
arr=np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [49]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [98]:
arr[:-1]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [66]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [70]:
b=[[1,2,3],[10,20,30],[11,12,13]]
c=np.array(b)
print(c)

[[ 1  2  3]
 [10 20 30]
 [11 12 13]]


In [73]:
d=c/a
print(d)

[[       inf 2.         1.5       ]
 [3.33333333 5.         6.        ]
 [1.83333333 1.71428571 1.625     ]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [72]:
e=c+1
print(e)

[[ 2  3  4]
 [11 21 31]
 [12 13 14]]


In [82]:
a=[1,2,3]
res=np.array(a)
print(np.sqrt(res))
print(np.sin(res))
print(np.cos(res))
print(np.tan(res))
print(np.log(res))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


AttributeError: module 'numpy' has no attribute 'sec'